#!/bin/bash -l
#
# ++++ THIS IS A CYLC JOB SCRIPT ++++
# Workflow: am5_c96L33_amip/run1
# Task: 19800101T0000Z/mask-atmos-plevel_atmos_scalar
# Job log directory: 19800101T0000Z/mask-atmos-plevel_atmos_scalar/01
# Job runner: ppan_handler
# Execution time limit: 14400.0

# DIRECTIVES:
#SBATCH --job-name=mask-atmos-plevel_atmos_scalar.19800101T0000Z.am5_c96L33_amip/run1
#SBATCH --output=cylc-run/am5_c96L33_amip/run1/log/job/19800101T0000Z/mask-atmos-plevel_atmos_scalar/01/job.out
#SBATCH --error=cylc-run/am5_c96L33_amip/run1/log/job/19800101T0000Z/mask-atmos-plevel_atmos_scalar/01/job.err
#SBATCH --time=240:00
#SBATCH --comment=xtmp,epmt,canopy
if [[ $1 == 'noreinvoke' ]]; then
    shift
else
    exec bash -l "$0" noreinvoke "$@"
fi

CYLC_FAIL_SIGNALS='EXIT ERR TERM XCPU'
export PATH=/home/fms/fre-canopy/system-settings/bin:$PATH
export CYLC_VERBOSE=false
export CYLC_DEBUG=false
export CYLC_VERSION='8.2.1'
export CYLC_WORKFLOW_ID="am5_c96L33_amip/run1"

cylc__job__inst__cylc_env() {
    # CYLC WORKFLOW ENVIRONMENT:
    export CYLC_CYCLING_MODE="gregorian"
    export CYLC_UTC="True"
    export CYLC_WORKFLOW_FINAL_CYCLE_POINT="19810101T0000Z"
    export CYLC_WORKFLOW_INITIAL_CYCLE_POINT="19800101T0000Z"
    export CYLC_WORKFLOW_NAME="am5_c96L33_amip"
    export CYLC_WORKFLOW_NAME_BASE="am5_c96L33_amip"
    export TZ="UTC"
    export CYLC_WORKFLOW_UUID="3597f5ac-5703-4961-9c09-d98b5fa2d34f"

    # CYLC TASK ENVIRONMENT:
    export CYLC_TASK_COMMS_METHOD=zmq
    export CYLC_TASK_JOB="19800101T0000Z/mask-atmos-plevel_atmos_scalar/01"
    export CYLC_TASK_NAMESPACE_HIERARCHY="root _atmos_scalar MASK-ATMOS-PLEVEL mask-atmos-plevel_atmos_scalar"
    export CYLC_TASK_DEPENDENCIES="19800101T0000Z/stage-history 19800101T0000Z/stage-history-refined"
    export CYLC_TASK_TRY_NUMBER=1
    export CYLC_TASK_FLOW_NUMBERS=1
    export CYLC_TASK_PARAM_native="atmos_scalar"
}

cylc__job__inst__user_env() {
    # TASK RUNTIME ENVIRONMENT:
    export COPY_TOOL inputDir component
    COPY_TOOL="gcp"
    inputDir="$CYLC_WORKFLOW_SHARE_DIR/cycle/$CYLC_TASK_CYCLE_POINT/history/native"
    component="$CYLC_TASK_PARAM_native"
}

cylc__job__inst__init_script() {
# INIT-SCRIPT:
module load ppan_environment
module load epmt
module list
epmt check
}

cylc__job__inst__env_script() {
# ENV-SCRIPT:
eval $(rose task-env)
env
export PAPIEX_OLD_OUTPUT=$PAPIEX_OUTPUT
export PAPIEX_OLD_OPTIONS=$PAPIEX_OPTIONS
unset PAPIEX_OUTPUT PAPIEX_OPTIONS LD_PRELOAD
epmt annotate EPMT_JOB_TAGS="exp_name:am5_c96L33_amip;exp_platform:gfdl.ncrc5-intel22-classic;exp_target:prod-openmp;exp_component:atmos_scalar;exp_component_source:atmos_scalar;exp_time:$CYLC_TASK_CYCLE_POINT;exp_seg_months:12;pp_chunk_a_months:24;pp_chunk_b_months:48;script_name:$CYLC_TASK_NAME;pp_is_canopy:YES"
export PAPIEX_OPTIONS=$PAPIEX_OLD_OPTIONS
export LD_PRELOAD=$PAPIEX_LD_PRELOAD
export PAPIEX_OUTPUT=$PAPIEX_OLD_OUTPUT
}

cylc__job__inst__pre_script() {
# PRE-SCRIPT:
module load python
}

cylc__job__inst__script() {
# SCRIPT:
export PAPIEX_TAGS="op:plevel;op_instance:1"; rose task-run --verbose --app-key mask-atmos-plevel; unset PAPIEX_TAGS;
}

CYLC_RUN_DIR="${CYLC_RUN_DIR:-$HOME/cylc-run}"
. "${CYLC_RUN_DIR}/${CYLC_WORKFLOW_ID}/.service/etc/job.sh"
cylc__job__main

#EOF: 19800101T0000Z/mask-atmos-plevel_atmos_scalar/01
