name: fre-workflows
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - cdo
  - cylc-flow
  - fre-cli
  - metomi-rose
  - nccmp
  - nco
  - pip
  - python
  - pyyaml
  - pylint
  - pytest
  - setuptools<81
