#!/app/conda/miniconda/envs/python-3.9-20220720/bin/python
#/bin/python
from pathlib import Path
import pytest
import subprocess, os

#DATA_DIR  = Path("test-data")
#DATA_FILE_BK = Path("atmos_tracer.bk.cdl")
#DATA_FILE_BK_NC = Path("atmos_tracer.bk.nc")

DATA_DIR="/home/Dana.Singh/pp/refactor/remap-python/app/remap-pp-components/test-data"
DATA_FILE_BK = DATA_DIR+"/atmos_trace.bk.cdl"
DATA_FILE_BK_NC = DATA_DIR+"/atmos_tracer.bk.nc"

print(DATA_FILE_BK)

#have to update paths for pp data

###############
#TEST1: checks for success of remapping a file based on a default outputDRS 

#TEST2: app checks for success of remapping a file with rose app as the valid definitions are being called by the environment.

#TEST3: compares the results of both above tests making sure that the two new created remapped files are identical.
