# directories shared across tools
directories:
  history_dir:        "/mnt/history"
  pp_dir:             "/mnt/pp"
#  analysis_dir:       !join [/nbhome/$USER/, *FRE_STEM, /, *name]
  ptmp_dir:           "/mnt/ptmp"

postprocess:
  settings:
    history_segment:         "P1Y"
    site:                    "ppp-container"
    pp_chunks:               [*PP_CHUNK96]
    pp_start:                *EXP_AMIP_START
    pp_stop:                 *EXP_AMIP_END
    pp_grid_spec:            *GRID_SPEC96
  switches:
    clean_work:              True
    do_atmos_plevel_masking: True
    do_analysis:             False
    do_analysis_only:        False
  preanalysis:
    vitals:
      script:                "$CYLC_WORKFLOW_RUN_DIR/etc/preAnalysis/dummy.csh"
      inputs:                 ['atmos_month']
      do_preanalysis:        True
  refinediag:
    atmos:
      script:                "$CYLC_WORKFLOW_RUN_DIR/etc/refineDiag/dummy.csh"
      inputs:                 ['atmos_month']
      outputs:                ['atmos_refined']
      do_refinediag:         True
